"""Type stubs for the mrrc native extension module."""

from typing import Iterator, Optional, List, Union, BinaryIO, Any

# =============================================================================
# Core Data Types
# =============================================================================

class Subfield:
    """A MARC subfield with code and value."""
    code: str
    value: str
    def __init__(self, code: str, value: str) -> None: ...

class Leader:
    """MARC record leader (24 characters)."""
    record_length: int
    record_status: str
    record_type: str
    bibliographic_level: str
    control_record_type: str
    character_coding: str
    indicator_count: int
    subfield_code_count: int
    data_base_address: int
    encoding_level: str
    cataloging_form: str
    multipart_level: str
    reserved: str

    def __init__(self) -> None: ...
    @staticmethod
    def get_valid_values(position: int) -> Optional[dict[str, str]]: ...
    @staticmethod
    def describe_value(position: int, value: str) -> Optional[str]: ...
    @staticmethod
    def is_valid_value(position: int, value: str) -> bool: ...

class Field:
    """A MARC data field with tag, indicators, and subfields."""
    tag: str
    indicator1: str
    indicator2: str

    def __init__(self, tag: str, indicator1: str = " ", indicator2: str = " ") -> None: ...
    def add_subfield(self, code: str, value: str) -> None: ...
    def subfields(self) -> List[Subfield]: ...
    def subfields_by_code(self, code: str) -> List[str]: ...

class Record:
    """A MARC bibliographic record."""
    def __init__(self, leader: Optional[Leader] = None) -> None: ...
    def leader(self) -> Leader: ...
    def set_leader(self, leader: Leader) -> None: ...
    def add_field(self, field: Field) -> None: ...
    def add_control_field(self, tag: str, value: str) -> None: ...
    def control_field(self, tag: str) -> Optional[str]: ...
    def control_fields(self) -> List[tuple[str, str]]: ...
    def get_field(self, tag: str) -> Optional[Field]: ...
    def get_fields(self, tag: str) -> List[Field]: ...
    def fields(self) -> List[Field]: ...
    def remove_field(self, tag: str) -> None: ...
    def fields_by_indicator(
        self, tag: str, *, indicator1: Optional[str] = None, indicator2: Optional[str] = None
    ) -> List[Field]: ...
    def fields_in_range(self, start_tag: str, end_tag: str) -> List[Field]: ...
    def fields_matching(self, query: FieldQuery) -> List[Field]: ...
    def fields_matching_range(self, query: TagRangeQuery) -> List[Field]: ...
    def fields_matching_pattern(self, query: SubfieldPatternQuery) -> List[Field]: ...
    def fields_matching_value(self, query: SubfieldValueQuery) -> List[Field]: ...
    def title(self) -> Optional[str]: ...
    def author(self) -> Optional[str]: ...
    def isbn(self) -> Optional[str]: ...
    def issn(self) -> Optional[str]: ...
    def subjects(self) -> List[str]: ...
    def location(self) -> List[str]: ...
    def notes(self) -> List[str]: ...
    def publisher(self) -> Optional[str]: ...
    def uniform_title(self) -> Optional[str]: ...
    def sudoc(self) -> Optional[str]: ...
    def issn_title(self) -> Optional[str]: ...
    def issnl(self) -> Optional[str]: ...
    def pubyear(self) -> Optional[int]: ...
    def series(self) -> Optional[str]: ...
    def physical_description(self) -> Optional[str]: ...
    def is_book(self) -> bool: ...
    def is_serial(self) -> bool: ...
    def is_music(self) -> bool: ...
    def is_audiovisual(self) -> bool: ...
    def to_json(self) -> str: ...
    def to_xml(self) -> str: ...
    def to_dublin_core(self) -> str: ...
    def to_marcjson(self) -> str: ...

class AuthorityRecord:
    """A MARC authority record."""
    def leader(self) -> Leader: ...
    def fields(self) -> List[Field]: ...
    def get_field(self, tag: str) -> Optional[Field]: ...
    def get_fields(self, tag: str) -> List[Field]: ...
    def control_field(self, tag: str) -> Optional[str]: ...

class HoldingsRecord:
    """A MARC holdings record."""
    def leader(self) -> Leader: ...
    def fields(self) -> List[Field]: ...
    def get_field(self, tag: str) -> Optional[Field]: ...
    def get_fields(self, tag: str) -> List[Field]: ...
    def control_field(self, tag: str) -> Optional[str]: ...

# =============================================================================
# Query DSL Classes
# =============================================================================

class FieldQuery:
    """Query builder for matching fields by tag, indicators, and subfields."""
    def __init__(self) -> None: ...
    def tag(self, tag: str) -> FieldQuery: ...
    def indicator1(self, value: str) -> FieldQuery: ...
    def indicator2(self, value: str) -> FieldQuery: ...
    def has_subfield(self, code: str) -> FieldQuery: ...

class TagRangeQuery:
    """Query for fields within a tag range."""
    def __init__(
        self,
        start_tag: str,
        end_tag: str,
        *,
        indicator1: Optional[str] = None,
        indicator2: Optional[str] = None,
        required_subfields: Optional[List[str]] = None,
    ) -> None: ...

class SubfieldPatternQuery:
    """Query for fields where a subfield matches a regex pattern."""
    def __init__(self, tag: str, subfield_code: str, pattern: str) -> None: ...

class SubfieldValueQuery:
    """Query for fields where a subfield matches a value."""
    def __init__(
        self, tag: str, subfield_code: str, value: str, *, partial: bool = False
    ) -> None: ...

# =============================================================================
# ISO 2709 MARC Readers and Writers
# =============================================================================

class MARCReader:
    """Reader for ISO 2709 binary MARC files."""
    def __init__(self, file: BinaryIO) -> None: ...
    def __iter__(self) -> Iterator[Record]: ...
    def __next__(self) -> Record: ...
    def read_record(self) -> Optional[Record]: ...
    def records_read(self) -> int: ...

class MARCWriter:
    """Writer for ISO 2709 binary MARC files."""
    def __init__(self, file: BinaryIO) -> None: ...
    def write_record(self, record: Record) -> None: ...
    def write(self, record: Record) -> None: ...
    def close(self) -> None: ...
    def records_written(self) -> int: ...

class AuthorityMARCReader:
    """Reader for MARC authority records."""
    def __init__(self, file: BinaryIO) -> None: ...
    def __iter__(self) -> Iterator[AuthorityRecord]: ...
    def __next__(self) -> AuthorityRecord: ...

class HoldingsMARCReader:
    """Reader for MARC holdings records."""
    def __init__(self, file: BinaryIO) -> None: ...
    def __iter__(self) -> Iterator[HoldingsRecord]: ...
    def __next__(self) -> HoldingsRecord: ...

# =============================================================================
# Format Conversion Functions
# =============================================================================

def record_to_json(record: Record) -> str: ...
def json_to_record(json_str: str) -> Record: ...
def record_to_xml(record: Record) -> str: ...
def xml_to_record(xml_str: str) -> Record: ...
def record_to_marcjson(record: Record) -> str: ...
def marcjson_to_record(json_str: str) -> Record: ...
def record_to_dublin_core(record: Record) -> str: ...
def record_to_dublin_core_xml(record: Record) -> str: ...
def record_to_mods(record: Record) -> str: ...
def dublin_core_to_xml(dc_str: str) -> str: ...
def record_to_csv(record: Record, fields: List[str]) -> str: ...
def records_to_csv(records: List[Record], fields: List[str]) -> str: ...
def records_to_csv_filtered(
    records: List[Record], fields: List[str], filter_fn: Any
) -> str: ...

# =============================================================================
# BIBFRAME Conversion
# =============================================================================

class BibframeConfig:
    """Configuration for BIBFRAME conversion."""
    def __init__(self) -> None: ...
    def with_base_uri(self, uri: str) -> BibframeConfig: ...
    def with_output_format(self, format: str) -> BibframeConfig: ...
    def with_authority_linking(self, enabled: bool) -> BibframeConfig: ...

class RdfGraph:
    """An RDF graph containing BIBFRAME triples."""
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def serialize(self, format: str) -> str: ...

def marc_to_bibframe(record: Record, config: BibframeConfig) -> RdfGraph: ...
def bibframe_to_marc(graph: RdfGraph) -> Record: ...

# =============================================================================
# Parallel Processing Utilities
# =============================================================================

class RecordBoundaryScanner:
    """Scanner for finding record boundaries in MARC data."""
    def __init__(self, data: bytes) -> None: ...
    def scan(self) -> List[tuple[int, int]]: ...

class ProducerConsumerPipeline:
    """Pipeline for parallel record processing."""
    def __init__(self, num_workers: int = 4) -> None: ...

def parse_batch_parallel(data: bytes) -> List[Record]: ...
def parse_batch_parallel_limited(data: bytes, max_records: int) -> List[Record]: ...
