#!/usr/bin/env python3
"""Regenerate the MARC-8 decode tables in src/marc8_tables.rs.

The tables come from pymarc's ``marc8_mapping`` module, which is itself
generated from the Library of Congress MARC-8 code tables
(https://www.loc.gov/marc/specifications/codetables.xml). Each table maps a
byte (or, for EACC, a 3-byte sequence packed into a u32) to a Unicode code
point and a flag marking combining characters.

Keys keep the positions the code tables assign: sets normally designated as
G0 are keyed 0x21-0x7E, and ANSEL and the extended sets normally designated
as G1 are keyed 0xA1-0xFE. The decoder resolves a byte from the other half by
flipping its high bit.

pymarc's ``ODD_MAP`` (a handful of vendor-specific 3-byte codes) is merged
into the EACC table, because pymarc consults it only when a multibyte lookup
misses.

Run from the repository root with the oracle extra installed:

    uv run python scripts/generate_marc8_tables.py

The script rewrites the region between the BEGIN/END GENERATED markers in
src/marc8_tables.rs and leaves the rest of the file untouched.
"""

from __future__ import annotations

import pathlib
import unicodedata

from pymarc import marc8_mapping

TARGET = pathlib.Path("src/marc8_tables.rs")
BEGIN = "// BEGIN GENERATED MARC-8 TABLES"
END = "// END GENERATED MARC-8 TABLES"

# (static name, final byte, description) for each single-byte set.
SINGLE_BYTE_SETS = [
    ("BASIC_LATIN", 0x42, "Basic Latin (ASCII)"),
    ("ANSEL_EXTENDED_LATIN", 0x45, "ANSEL Extended Latin"),
    ("BASIC_HEBREW", 0x32, "Basic Hebrew"),
    ("BASIC_ARABIC", 0x33, "Basic Arabic"),
    ("EXTENDED_ARABIC", 0x34, "Extended Arabic"),
    ("BASIC_CYRILLIC", 0x4E, "Basic Cyrillic"),
    ("EXTENDED_CYRILLIC", 0x51, "Extended Cyrillic"),
    ("BASIC_GREEK", 0x53, "Basic Greek"),
    ("GREEK_SYMBOLS", 0x67, "Greek Symbols"),
    ("SUBSCRIPT", 0x62, "Subscripts"),
    ("SUPERSCRIPT", 0x70, "Superscripts"),
]


def _name(code_point: int) -> str:
    return unicodedata.name(chr(code_point), f"U+{code_point:04X}")


def _single_byte_table(name: str, final: int, description: str) -> list[str]:
    table = marc8_mapping.CODESETS[final]
    lines = [
        f"/// {description} - final byte 0x{final:02X} ({len(table)} mappings)",
        f"static {name}: LazyLock<HashMap<u8, CharacterMapping>> = LazyLock::new(|| {{",
        "    let mut m = HashMap::new();",
    ]
    for byte in sorted(table):
        code_point, combining = table[byte]
        lines.append(
            f"    m.insert(0x{byte:02X}, (0x{code_point:04X}, "
            f"{'true' if combining else 'false'})); // {_name(code_point)}"
        )
    lines += ["    m", "});", ""]
    return lines


def _eacc_table() -> list[str]:
    table = dict(marc8_mapping.CODESETS[0x31])
    odd = {k: (v, 0) for k, v in marc8_mapping.ODD_MAP.items() if k not in table}
    merged = {**table, **odd}
    lines = [
        "/// EACC (East Asian Character Code) - final byte 0x31",
        "/// Multi-byte character set (3 bytes per character) for Chinese, Japanese, Korean.",
        "/// Each entry maps a 3-byte sequence (concatenated as u32) to its Unicode equivalent:",
        f"/// {len(table)} EACC mappings plus {len(odd)} vendor-specific codes from pymarc's",
        "/// `ODD_MAP`, which pymarc consults only when an EACC lookup misses.",
        "/// Reference: <https://www.loc.gov/marc/specifications/specchareacc.html>",
        "static EACC_TABLE: LazyLock<HashMap<u32, CharacterMapping>> = LazyLock::new(|| {",
        "    let mut m = HashMap::new();",
    ]
    for key in sorted(merged):
        code_point, combining = merged[key]
        b1, b2, b3 = (key >> 16) & 0xFF, (key >> 8) & 0xFF, key & 0xFF
        lines.append(
            f"    m.insert(0x{b1:02X}_{b2:02X}_{b3:02X}, (0x{code_point:04X}, "
            f"{'true' if combining else 'false'}));"
        )
    lines += ["    m", "});"]
    return lines


def generate() -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/generate_marc8_tables.py from pymarc's marc8_mapping,",
        "// which is built from the Library of Congress MARC-8 code tables. Do not edit",
        "// by hand; rerun the script instead.",
        "",
    ]
    for name, final, description in SINGLE_BYTE_SETS:
        lines += _single_byte_table(name, final, description)
    lines += _eacc_table()
    lines.append(END)
    return "\n".join(lines)


def main() -> None:
    source = TARGET.read_text()
    start = source.index(BEGIN)
    end = source.index(END) + len(END)
    TARGET.write_text(source[:start] + generate() + source[end:])


if __name__ == "__main__":
    main()
